<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.17763.0</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <SupportedOSPlatformVersion>6.1</SupportedOSPlatformVersion>
    <RootNamespace>IES_2</RootNamespace>
    <AssemblyName>IES_2</AssemblyName>
    <ApplicationIcon>Res\MIL.ico</ApplicationIcon>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <!-- <Optimize Condition="'$(Configuration)' == 'Release'">true</Optimize> -->
    <!-- CA1416: Suppress platform-specific API warnings - this app targets Windows only -->
    <NoWarn>CA1416;CS8981</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <!-- <PackageReference Include="System.Configuration.ConfigurationManager" Version="10.0.5" /> -->
    <PackageReference Include="System.IO.Ports" Version="10.0.5" />
    <PackageReference Include="ZedGraph" Version="5.2.1" />
  </ItemGroup>

</Project>
