<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net10.0-android</TargetFrameworks>
    <OutputType>Exe</OutputType>
    <RootNamespace>IES_2.Droid</RootNamespace>
    <AssemblyName>IES_2.Droid</AssemblyName>
    <ApplicationId>com.ddiego74.ies2</ApplicationId>
    <ApplicationVersion>1</ApplicationVersion>
    <ApplicationDisplayVersion>0.86</ApplicationDisplayVersion>
    <AndroidMinSdkVersion>31</AndroidMinSdkVersion>
    <AndroidTargetSdkVersion>34</AndroidTargetSdkVersion>
    <SupportedOSPlatformVersion>31.0</SupportedOSPlatformVersion>
    <UseMaui>true</UseMaui>
    <SingleProject>true</SingleProject>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <MauiIcon Include="Resources\AppIcon\appicon.svg" ForegroundFile="Resources\AppIcon\appiconfg.svg" Color="#512BD4" />
    <MauiSplashScreen Include="Resources\Splash\splash.svg" Color="#512BD4" BaseSize="128,128" />
    <MauiImage Include="Resources\Images\*" />
    <MauiFont Include="Resources\Fonts\*" />
    <MauiAsset Include="Resources\Raw\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Maui.Controls" Version="10.0.20" />
    <PackageReference Include="Plugin.BLE" Version="3.1.0" />
    <PackageReference Include="LiveChartsCore.SkiaSharpView.Maui" Version="2.0.0-rc4" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\IES_2.Core\IES_2.Core.csproj" />
  </ItemGroup>
</Project>
